export {
  ENGINE_CONFIG,
} from './engine.config';

export {
  AUDIO_CONFIG,
  COIN_CONFIG,
  SHIELD_CONFIG,
  SPEED_BOOST_CONFIG,
  COLLISION_CONFIG,
  CONTROLS_CONFIG,
  COUNTDOWN_CONFIG,
  DIFFICULTY_CONFIG,
  OBSTACLE_PERSONALITY_CONFIG,
  GAME_CONFIG,
  HEALTH_CONFIG,
  SCORE_CONFIG,
  SPAWN_CONFIG,
} from './game.config';

export { DECORATION_CONFIG } from './decoration.config';

export {
  GRASS_IMAGE,
  ROAD_COLORS,
  ROAD_CONTROLS,
  ROAD_IMAGE,
  ROAD_LAYOUT,
  ROAD_PLAYER,
  ROAD_SCROLL,
  ROAD_TILE,
  ROAD_WORLD,
} from './road.config';
